// What the canvas may materialize, and every element's class.
//
// GENERATED from engine/ledger/ledger.json by projects/draw/tools/ledger-check.mjs --write.
// Do not edit: change the ledger and regenerate. The build fails if this file drifts from it.

export type LedgerClass = 'edit' | 'preserve' | 'preserve-hidden' | 'active' | 'drop';

/** Where an attribute applies: every element ('*') or a list; `except` elements have their own row. */
export interface AttrScope {
  readonly on: '*' | readonly string[];
  readonly except?: readonly string[];
}

/** SVG elements the canvas may materialize, through the safe sink. */
export const RENDER_SVG_ELEMENTS: ReadonlySet<string> = new Set([
  'a', 'altGlyph', 'animate', 'animateMotion', 'animateTransform', 'circle', 'clipPath', 'defs',
  'desc', 'ellipse', 'feBlend', 'feColorMatrix', 'feComponentTransfer', 'feComposite',
  'feConvolveMatrix', 'feDiffuseLighting', 'feDisplacementMap', 'feDistantLight', 'feDropShadow',
  'feFlood', 'feFuncA', 'feFuncB', 'feFuncG', 'feFuncR', 'feGaussianBlur', 'feImage', 'feMerge',
  'feMergeNode', 'feMorphology', 'feOffset', 'fePointLight', 'feSpecularLighting', 'feSpotLight',
  'feTile', 'feTurbulence', 'filter', 'foreignObject', 'g', 'image', 'line', 'linearGradient',
  'marker', 'mask', 'metadata', 'mpath', 'path', 'pattern', 'polygon', 'polyline',
  'radialGradient', 'rect', 'set', 'stop', 'style', 'svg', 'switch', 'symbol', 'text', 'textPath',
  'title', 'tref', 'tspan', 'use', 'view',
]);

/** XHTML elements the canvas may materialize inside <foreignObject>. */
export const RENDER_XHTML_ELEMENTS: ReadonlySet<string> = new Set([
  'a', 'abbr', 'address', 'article', 'aside', 'b', 'bdi', 'bdo', 'blockquote', 'br', 'caption',
  'cite', 'code', 'col', 'colgroup', 'data', 'dd', 'del', 'dfn', 'div', 'dl', 'dt', 'em',
  'figcaption', 'figure', 'footer', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'header', 'hr', 'i', 'img',
  'ins', 'kbd', 'li', 'main', 'mark', 'nav', 'ol', 'p', 'pre', 'q', 'rp', 'rt', 'ruby', 's',
  'samp', 'section', 'small', 'span', 'strong', 'sub', 'sup', 'table', 'tbody', 'td', 'tfoot',
  'th', 'thead', 'time', 'tr', 'u', 'ul', 'var', 'wbr',
]);

/** SVG attributes the canvas may materialize (XLink and XML ones as xlink:name and xml:name). */
export const RENDER_SVG_ATTRIBUTES: ReadonlyMap<string, AttrScope> = new Map<string, AttrScope>([
  ['accumulate', { on: ['animate', 'animateColor', 'animateMotion', 'animateTransform'] }],
  ['additive', { on: ['animate', 'animateColor', 'animateMotion', 'animateTransform'] }],
  ['alignment-baseline', { on: '*' }],
  ['amplitude', { on: ['feFuncA', 'feFuncB', 'feFuncG', 'feFuncR'] }],
  ['attributeName', { on: ['animate', 'animateColor', 'animateTransform', 'set'] }],
  ['attributeType', { on: ['animate', 'animateColor', 'animateTransform', 'set'] }],
  ['azimuth', { on: ['feDistantLight'] }],
  ['baseFrequency', { on: ['feTurbulence'] }],
  ['baseline-shift', { on: '*' }],
  ['begin', {
    on: [
      'animate', 'animateColor', 'animateMotion', 'animateTransform', 'animation', 'audio',
      'discard', 'set', 'video',
    ],
  }],
  ['bias', { on: ['feConvolveMatrix'] }],
  ['by', { on: ['animate', 'animateColor', 'animateMotion', 'animateTransform'] }],
  ['calcMode', { on: ['animate', 'animateColor', 'animateMotion', 'animateTransform'] }],
  ['class', { on: '*' }],
  ['clip', {
    on: [
      'a', 'altGlyph', 'animate', 'animateColor', 'circle', 'clipPath', 'defs', 'ellipse',
      'feBlend', 'feColorMatrix', 'feComponentTransfer', 'feComposite', 'feConvolveMatrix',
      'feDiffuseLighting', 'feDisplacementMap', 'feFlood', 'feGaussianBlur', 'feImage', 'feMerge',
      'feMorphology', 'feOffset', 'feSpecularLighting', 'feTile', 'feTurbulence', 'filter', 'font',
      'foreignObject', 'g', 'glyph', 'glyphRef', 'image', 'line', 'linearGradient', 'marker',
      'mask', 'missing-glyph', 'path', 'pattern', 'polygon', 'polyline', 'radialGradient', 'rect',
      'stop', 'svg', 'switch', 'symbol', 'text', 'textPath', 'tref', 'tspan', 'use',
    ],
  }],
  ['clip-path', { on: '*' }],
  ['clip-rule', { on: '*' }],
  ['clipPathUnits', { on: ['clipPath'] }],
  ['color', { on: '*' }],
  ['color-interpolation', { on: '*' }],
  ['color-interpolation-filters', { on: '*' }],
  ['color-rendering', { on: '*' }],
  ['cx', { on: ['circle', 'ellipse', 'radialGradient'] }],
  ['cy', { on: ['circle', 'ellipse', 'radialGradient'] }],
  ['d', { on: ['glyph', 'missing-glyph', 'path'] }],
  ['diffuseConstant', { on: ['feDiffuseLighting'] }],
  ['direction', { on: '*' }],
  ['display', { on: '*' }],
  ['divisor', { on: ['feConvolveMatrix'] }],
  ['dominant-baseline', { on: '*' }],
  ['dur', {
    on: [
      'animate', 'animateColor', 'animateMotion', 'animateTransform', 'animation', 'audio', 'set',
      'video',
    ],
  }],
  ['dx', { on: ['altGlyph', 'feDropShadow', 'feOffset', 'glyphRef', 'text', 'tref', 'tspan'] }],
  ['dy', { on: ['altGlyph', 'feDropShadow', 'feOffset', 'glyphRef', 'text', 'tref', 'tspan'] }],
  ['edgeMode', { on: ['feConvolveMatrix', 'feGaussianBlur'] }],
  ['elevation', { on: ['feDistantLight'] }],
  ['end', {
    on: [
      'animate', 'animateColor', 'animateMotion', 'animateTransform', 'animation', 'audio', 'set',
      'video',
    ],
  }],
  ['exponent', { on: ['feFuncA', 'feFuncB', 'feFuncG', 'feFuncR'] }],
  ['fill', { on: '*' }],
  ['fill-opacity', { on: '*' }],
  ['fill-rule', { on: '*' }],
  ['filter', { on: '*' }],
  ['filterUnits', { on: ['filter'] }],
  ['flood-color', { on: '*' }],
  ['flood-opacity', { on: '*' }],
  ['font-family', { on: '*' }],
  ['font-size', { on: '*' }],
  ['font-size-adjust', { on: '*' }],
  ['font-stretch', { on: '*' }],
  ['font-style', { on: '*' }],
  ['font-variant', { on: '*' }],
  ['font-weight', { on: '*' }],
  ['fr', { on: ['radialGradient'] }],
  ['from', { on: ['animate', 'animateColor', 'animateMotion', 'animateTransform'] }],
  ['fx', { on: ['radialGradient'] }],
  ['fy', { on: ['radialGradient'] }],
  ['glyph-orientation-horizontal', { on: '*' }],
  ['glyph-orientation-vertical', { on: '*' }],
  ['gradientTransform', { on: ['linearGradient', 'radialGradient'] }],
  ['gradientUnits', { on: ['linearGradient', 'radialGradient'] }],
  ['height', {
    on: [
      'animation', 'feBlend', 'feColorMatrix', 'feComponentTransfer', 'feComposite',
      'feConvolveMatrix', 'feDiffuseLighting', 'feDisplacementMap', 'feDropShadow', 'feFlood',
      'feGaussianBlur', 'feImage', 'feMerge', 'feMorphology', 'feOffset', 'feSpecularLighting',
      'feTile', 'feTurbulence', 'filter', 'foreignObject', 'image', 'mask', 'pattern', 'rect',
      'svg', 'symbol', 'textArea', 'use', 'video',
    ],
  }],
  ['href', {
    on: [
      'altGlyph', 'animate', 'animateMotion', 'animateTransform', 'discard', 'feImage', 'image',
      'linearGradient', 'mpath', 'pattern', 'radialGradient', 'script', 'set', 'textPath', 'tref',
      'use',
    ],
  }],
  ['id', { on: '*' }],
  ['image-rendering', { on: '*' }],
  ['in', {
    on: [
      'feBlend', 'feColorMatrix', 'feComponentTransfer', 'feComposite', 'feConvolveMatrix',
      'feDiffuseLighting', 'feDisplacementMap', 'feDropShadow', 'feGaussianBlur', 'feMergeNode',
      'feMorphology', 'feOffset', 'feSpecularLighting', 'feTile',
    ],
  }],
  ['in2', { on: ['feBlend', 'feComposite', 'feDisplacementMap'] }],
  ['intercept', { on: ['feFuncA', 'feFuncB', 'feFuncG', 'feFuncR'] }],
  ['k1', { on: ['feComposite'] }],
  ['k2', { on: ['feComposite'] }],
  ['k3', { on: ['feComposite'] }],
  ['k4', { on: ['feComposite'] }],
  ['kernelMatrix', { on: ['feConvolveMatrix'] }],
  ['kernelUnitLength', { on: ['feConvolveMatrix', 'feDiffuseLighting', 'feSpecularLighting'] }],
  ['kerning', {
    on: [
      'a', 'altGlyph', 'animate', 'animateColor', 'circle', 'clipPath', 'defs', 'ellipse',
      'feBlend', 'feColorMatrix', 'feComponentTransfer', 'feComposite', 'feConvolveMatrix',
      'feDiffuseLighting', 'feDisplacementMap', 'feFlood', 'feGaussianBlur', 'feImage', 'feMerge',
      'feMorphology', 'feOffset', 'feSpecularLighting', 'feTile', 'feTurbulence', 'filter', 'font',
      'foreignObject', 'g', 'glyph', 'glyphRef', 'image', 'line', 'linearGradient', 'marker',
      'mask', 'missing-glyph', 'path', 'pattern', 'polygon', 'polyline', 'radialGradient', 'rect',
      'stop', 'svg', 'switch', 'symbol', 'text', 'textPath', 'tref', 'tspan', 'use',
    ],
  }],
  ['keyPoints', { on: ['animateMotion'] }],
  ['keySplines', { on: ['animate', 'animateColor', 'animateMotion', 'animateTransform'] }],
  ['keyTimes', { on: ['animate', 'animateColor', 'animateMotion', 'animateTransform'] }],
  ['lang', { on: '*' }],
  ['lengthAdjust', { on: ['text', 'textPath', 'tref', 'tspan'] }],
  ['letter-spacing', { on: '*' }],
  ['lighting-color', { on: '*' }],
  ['limitingConeAngle', { on: ['feSpotLight'] }],
  ['marker-end', { on: '*' }],
  ['marker-mid', { on: '*' }],
  ['marker-start', { on: '*' }],
  ['markerHeight', { on: ['marker'] }],
  ['markerUnits', { on: ['marker'] }],
  ['markerWidth', { on: ['marker'] }],
  ['mask', { on: '*' }],
  ['mask-type', { on: ['mask'] }],
  ['maskContentUnits', { on: ['mask'] }],
  ['maskUnits', { on: ['mask'] }],
  ['max', {
    on: [
      'animate', 'animateColor', 'animateMotion', 'animateTransform', 'animation', 'audio', 'set',
      'video',
    ],
  }],
  ['media', { on: ['style'] }],
  ['method', { on: ['textPath'] }],
  ['min', {
    on: [
      'animate', 'animateColor', 'animateMotion', 'animateTransform', 'animation', 'audio', 'set',
      'video',
    ],
  }],
  ['mode', { on: ['feBlend'] }],
  ['numOctaves', { on: ['feTurbulence'] }],
  ['offset', { on: ['feFuncA', 'feFuncB', 'feFuncG', 'feFuncR', 'stop'] }],
  ['opacity', { on: '*' }],
  ['operator', { on: ['feComposite', 'feMorphology'] }],
  ['order', { on: ['feConvolveMatrix'] }],
  ['orient', { on: ['marker'] }],
  ['overflow', { on: '*' }],
  ['paint-order', { on: '*' }],
  ['path', { on: ['animateMotion', 'textPath'] }],
  ['pathLength', { on: ['circle', 'ellipse', 'line', 'path', 'polygon', 'polyline', 'rect'] }],
  ['patternContentUnits', { on: ['pattern'] }],
  ['patternTransform', { on: ['pattern'] }],
  ['patternUnits', { on: ['pattern'] }],
  ['points', { on: ['polygon', 'polyline'] }],
  ['pointsAtX', { on: ['feSpotLight'] }],
  ['pointsAtY', { on: ['feSpotLight'] }],
  ['pointsAtZ', { on: ['feSpotLight'] }],
  ['preserveAlpha', { on: ['feConvolveMatrix'] }],
  ['preserveAspectRatio', {
    on: [
      'animation', 'canvas', 'feImage', 'image', 'marker', 'pattern', 'svg', 'symbol', 'video',
      'view',
    ],
  }],
  ['primitiveUnits', { on: ['filter'] }],
  ['r', { on: ['circle', 'radialGradient'] }],
  ['radius', { on: ['feMorphology'] }],
  ['refX', { on: ['marker', 'symbol'] }],
  ['refY', { on: ['marker', 'symbol'] }],
  ['repeatCount', {
    on: [
      'animate', 'animateColor', 'animateMotion', 'animateTransform', 'animation', 'audio', 'set',
      'video',
    ],
  }],
  ['repeatDur', {
    on: [
      'animate', 'animateColor', 'animateMotion', 'animateTransform', 'animation', 'audio', 'set',
      'video',
    ],
  }],
  ['requiredExtensions', {
    on: [
      'a', 'altGlyph', 'animate', 'animateColor', 'animateMotion', 'animateTransform', 'animation',
      'audio', 'canvas', 'circle', 'clipPath', 'cursor', 'defs', 'desc', 'discard', 'ellipse',
      'foreignObject', 'g', 'iframe', 'image', 'line', 'mask', 'metadata', 'path', 'pattern',
      'polygon', 'polyline', 'rect', 'set', 'svg', 'switch', 'tbreak', 'text', 'textArea',
      'textPath', 'title', 'tref', 'tspan', 'unknown', 'use', 'video',
    ],
  }],
  ['requiredFeatures', {
    on: [
      'a', 'altGlyph', 'animate', 'animateColor', 'animateMotion', 'animateTransform', 'animation',
      'audio', 'circle', 'clipPath', 'cursor', 'defs', 'desc', 'discard', 'ellipse',
      'foreignObject', 'g', 'image', 'line', 'mask', 'metadata', 'path', 'pattern', 'polygon',
      'polyline', 'rect', 'set', 'svg', 'switch', 'tbreak', 'text', 'textArea', 'textPath',
      'title', 'tref', 'tspan', 'use', 'video',
    ],
  }],
  ['restart', {
    on: [
      'animate', 'animateColor', 'animateMotion', 'animateTransform', 'animation', 'audio', 'set',
      'video',
    ],
  }],
  ['result', {
    on: [
      'feBlend', 'feColorMatrix', 'feComponentTransfer', 'feComposite', 'feConvolveMatrix',
      'feDiffuseLighting', 'feDisplacementMap', 'feDropShadow', 'feFlood', 'feGaussianBlur',
      'feImage', 'feMerge', 'feMorphology', 'feOffset', 'feSpecularLighting', 'feTile',
      'feTurbulence',
    ],
  }],
  ['role', { on: '*' }],
  ['rotate', { on: ['altGlyph', 'animateMotion', 'text', 'tref', 'tspan'] }],
  ['rx', { on: ['ellipse', 'rect'] }],
  ['ry', { on: ['ellipse', 'rect'] }],
  ['scale', { on: ['feDisplacementMap'] }],
  ['seed', { on: ['feTurbulence'] }],
  ['shape-rendering', { on: '*' }],
  ['side', { on: ['textPath'] }],
  ['slope', { on: ['feFuncA', 'feFuncB', 'feFuncG', 'feFuncR'] }],
  ['spacing', { on: ['textPath'] }],
  ['specularConstant', { on: ['feSpecularLighting'] }],
  ['specularExponent', { on: ['feSpecularLighting', 'feSpotLight'] }],
  ['spreadMethod', { on: ['linearGradient', 'radialGradient'] }],
  ['startOffset', { on: ['textPath'] }],
  ['stdDeviation', { on: ['feDropShadow', 'feGaussianBlur'] }],
  ['stitchTiles', { on: ['feTurbulence'] }],
  ['stop-color', { on: '*' }],
  ['stop-opacity', { on: '*' }],
  ['stroke', { on: '*' }],
  ['stroke-dasharray', { on: '*' }],
  ['stroke-dashoffset', { on: '*' }],
  ['stroke-linecap', { on: '*' }],
  ['stroke-linejoin', { on: '*' }],
  ['stroke-miterlimit', { on: '*' }],
  ['stroke-opacity', { on: '*' }],
  ['stroke-width', { on: '*' }],
  ['style', { on: '*' }],
  ['surfaceScale', { on: ['feDiffuseLighting', 'feSpecularLighting'] }],
  ['systemLanguage', {
    on: [
      'a', 'altGlyph', 'animate', 'animateColor', 'animateMotion', 'animateTransform', 'animation',
      'audio', 'canvas', 'circle', 'clipPath', 'cursor', 'defs', 'desc', 'discard', 'ellipse',
      'foreignObject', 'g', 'iframe', 'image', 'line', 'mask', 'metadata', 'path', 'pattern',
      'polygon', 'polyline', 'rect', 'set', 'svg', 'switch', 'tbreak', 'text', 'textArea',
      'textPath', 'title', 'tref', 'tspan', 'unknown', 'use', 'video',
    ],
  }],
  ['tableValues', { on: ['feFuncA', 'feFuncB', 'feFuncG', 'feFuncR'] }],
  ['targetX', { on: ['feConvolveMatrix'] }],
  ['targetY', { on: ['feConvolveMatrix'] }],
  ['text-anchor', { on: '*' }],
  ['text-decoration', { on: '*' }],
  ['text-overflow', { on: '*' }],
  ['text-rendering', { on: '*' }],
  ['textLength', { on: ['text', 'textPath', 'tref', 'tspan'] }],
  ['title', { on: ['style'] }],
  ['to', { on: ['animate', 'animateColor', 'animateMotion', 'animateTransform', 'set'] }],
  ['transform', { on: '*' }],
  ['transform-origin', { on: '*' }],
  ['type', {
    on: [
      'animateTransform', 'feColorMatrix', 'feFuncA', 'feFuncB', 'feFuncG', 'feFuncR',
      'feTurbulence', 'style',
    ],
  }],
  ['unicode-bidi', { on: '*' }],
  ['values', {
    on: [
      'animate', 'animateColor', 'animateMotion', 'animateTransform', 'feColorMatrix',
    ],
  }],
  ['vector-effect', { on: '*' }],
  ['viewBox', { on: ['marker', 'pattern', 'svg', 'symbol', 'view'] }],
  ['visibility', { on: '*' }],
  ['white-space', { on: '*' }],
  ['width', {
    on: [
      'animation', 'feBlend', 'feColorMatrix', 'feComponentTransfer', 'feComposite',
      'feConvolveMatrix', 'feDiffuseLighting', 'feDisplacementMap', 'feDropShadow', 'feFlood',
      'feGaussianBlur', 'feImage', 'feMerge', 'feMorphology', 'feOffset', 'feSpecularLighting',
      'feTile', 'feTurbulence', 'filter', 'foreignObject', 'image', 'mask', 'pattern', 'rect',
      'svg', 'symbol', 'textArea', 'use', 'video',
    ],
  }],
  ['word-spacing', { on: '*' }],
  ['writing-mode', { on: '*' }],
  ['x', {
    on: [
      'altGlyph', 'animation', 'cursor', 'feBlend', 'feColorMatrix', 'feComponentTransfer',
      'feComposite', 'feConvolveMatrix', 'feDiffuseLighting', 'feDisplacementMap', 'feDropShadow',
      'feFlood', 'feGaussianBlur', 'feImage', 'feMerge', 'feMorphology', 'feOffset',
      'fePointLight', 'feSpecularLighting', 'feSpotLight', 'feTile', 'feTurbulence', 'filter',
      'foreignObject', 'glyphRef', 'image', 'mask', 'pattern', 'rect', 'svg', 'symbol', 'text',
      'textArea', 'tref', 'tspan', 'use', 'video',
    ],
  }],
  ['x1', { on: ['line', 'linearGradient'] }],
  ['x2', { on: ['line', 'linearGradient'] }],
  ['xChannelSelector', { on: ['feDisplacementMap'] }],
  ['xlink:href', { on: '*', except: ['a'] }],
  ['xml:lang', { on: '*' }],
  ['xml:space', { on: '*' }],
  ['y', {
    on: [
      'altGlyph', 'animation', 'cursor', 'feBlend', 'feColorMatrix', 'feComponentTransfer',
      'feComposite', 'feConvolveMatrix', 'feDiffuseLighting', 'feDisplacementMap', 'feDropShadow',
      'feFlood', 'feGaussianBlur', 'feImage', 'feMerge', 'feMorphology', 'feOffset',
      'fePointLight', 'feSpecularLighting', 'feSpotLight', 'feTile', 'feTurbulence', 'filter',
      'foreignObject', 'glyphRef', 'image', 'mask', 'pattern', 'rect', 'svg', 'symbol', 'text',
      'textArea', 'tref', 'tspan', 'use', 'video',
    ],
  }],
  ['y1', { on: ['line', 'linearGradient'] }],
  ['y2', { on: ['line', 'linearGradient'] }],
  ['yChannelSelector', { on: ['feDisplacementMap'] }],
  ['z', { on: ['fePointLight', 'feSpotLight'] }],
]);

/** No-namespace SVG attribute names the canvas may materialize on any element, by pattern. */
export const RENDER_SVG_ATTRIBUTE_PATTERNS: readonly RegExp[] = [
  /^aria-[a-z]+$/, // aria-*
  /^data-[^\s:]+$/, // data-*
];

/** XHTML attributes the canvas may materialize inside <foreignObject>. */
export const RENDER_XHTML_ATTRIBUTES: ReadonlyMap<string, AttrScope> = new Map<string, AttrScope>([
  ['align', { on: '*' }],
  ['alt', { on: ['img'] }],
  ['bgcolor', { on: ['table', 'td', 'th', 'tr'] }],
  ['border', { on: ['img', 'table'] }],
  ['cellpadding', { on: ['table'] }],
  ['cellspacing', { on: ['table'] }],
  ['class', { on: '*' }],
  ['colspan', { on: ['td', 'th'] }],
  ['dir', { on: '*' }],
  ['height', { on: ['img', 'table', 'td', 'th', 'tr'] }],
  ['hidden', { on: '*' }],
  ['id', { on: '*' }],
  ['lang', { on: '*' }],
  ['reversed', { on: ['ol'] }],
  ['rowspan', { on: ['td', 'th'] }],
  ['span', { on: ['col', 'colgroup'] }],
  ['src', { on: ['img'] }],
  ['start', { on: ['ol'] }],
  ['style', { on: '*' }],
  ['title', { on: '*' }],
  ['valign', { on: ['col', 'colgroup', 'tbody', 'td', 'tfoot', 'th', 'thead', 'tr'] }],
  ['value', { on: ['li'] }],
  ['width', { on: ['col', 'img', 'table', 'td', 'th'] }],
]);

/** XHTML attribute names the canvas may materialize on any element inside <foreignObject>, by pattern. */
export const RENDER_XHTML_ATTRIBUTE_PATTERNS: readonly RegExp[] = [

];

/** Every classified element, as 'ns:name'. Fallbacks: 'svg:*', 'xhtml:*', 'mathml:*' and '*:*'. */
export const ELEMENT_CLASS: ReadonlyMap<string, LedgerClass> = new Map<string, LedgerClass>([
  ['*:*', 'preserve-hidden'],
  ['mathml:*', 'preserve-hidden'],
  ['svg:*', 'preserve-hidden'],
  ['svg:a', 'edit'],
  ['svg:altGlyph', 'preserve'],
  ['svg:altGlyphDef', 'preserve-hidden'],
  ['svg:altGlyphItem', 'preserve-hidden'],
  ['svg:animate', 'edit'],
  ['svg:animateColor', 'preserve-hidden'],
  ['svg:animateMotion', 'edit'],
  ['svg:animateTransform', 'edit'],
  ['svg:animation', 'active'],
  ['svg:audio', 'active'],
  ['svg:canvas', 'preserve-hidden'],
  ['svg:circle', 'edit'],
  ['svg:clipPath', 'edit'],
  ['svg:color-profile', 'preserve-hidden'],
  ['svg:cursor', 'preserve-hidden'],
  ['svg:defs', 'edit'],
  ['svg:desc', 'edit'],
  ['svg:discard', 'preserve-hidden'],
  ['svg:ellipse', 'edit'],
  ['svg:feBlend', 'edit'],
  ['svg:feColorMatrix', 'edit'],
  ['svg:feComponentTransfer', 'edit'],
  ['svg:feComposite', 'edit'],
  ['svg:feConvolveMatrix', 'edit'],
  ['svg:feDiffuseLighting', 'edit'],
  ['svg:feDisplacementMap', 'edit'],
  ['svg:feDistantLight', 'edit'],
  ['svg:feDropShadow', 'edit'],
  ['svg:feFlood', 'edit'],
  ['svg:feFuncA', 'edit'],
  ['svg:feFuncB', 'edit'],
  ['svg:feFuncG', 'edit'],
  ['svg:feFuncR', 'edit'],
  ['svg:feGaussianBlur', 'edit'],
  ['svg:feImage', 'edit'],
  ['svg:feMerge', 'edit'],
  ['svg:feMergeNode', 'edit'],
  ['svg:feMorphology', 'edit'],
  ['svg:feOffset', 'edit'],
  ['svg:fePointLight', 'edit'],
  ['svg:feSpecularLighting', 'edit'],
  ['svg:feSpotLight', 'edit'],
  ['svg:feTile', 'edit'],
  ['svg:feTurbulence', 'edit'],
  ['svg:filter', 'edit'],
  ['svg:font', 'preserve-hidden'],
  ['svg:font-face', 'preserve-hidden'],
  ['svg:font-face-format', 'preserve-hidden'],
  ['svg:font-face-name', 'preserve-hidden'],
  ['svg:font-face-src', 'preserve-hidden'],
  ['svg:font-face-uri', 'preserve-hidden'],
  ['svg:foreignObject', 'edit'],
  ['svg:g', 'edit'],
  ['svg:glyph', 'preserve-hidden'],
  ['svg:glyphRef', 'preserve-hidden'],
  ['svg:handler', 'active'],
  ['svg:hkern', 'preserve-hidden'],
  ['svg:iframe', 'active'],
  ['svg:image', 'edit'],
  ['svg:line', 'edit'],
  ['svg:linearGradient', 'edit'],
  ['svg:listener', 'active'],
  ['svg:marker', 'edit'],
  ['svg:mask', 'edit'],
  ['svg:metadata', 'edit'],
  ['svg:missing-glyph', 'preserve-hidden'],
  ['svg:mpath', 'edit'],
  ['svg:path', 'edit'],
  ['svg:pattern', 'edit'],
  ['svg:polygon', 'edit'],
  ['svg:polyline', 'edit'],
  ['svg:prefetch', 'active'],
  ['svg:radialGradient', 'edit'],
  ['svg:rect', 'edit'],
  ['svg:script', 'active'],
  ['svg:set', 'edit'],
  ['svg:solidColor', 'preserve-hidden'],
  ['svg:stop', 'edit'],
  ['svg:style', 'edit'],
  ['svg:svg', 'edit'],
  ['svg:switch', 'edit'],
  ['svg:symbol', 'edit'],
  ['svg:tbreak', 'preserve-hidden'],
  ['svg:text', 'edit'],
  ['svg:textArea', 'preserve-hidden'],
  ['svg:textPath', 'edit'],
  ['svg:title', 'edit'],
  ['svg:tref', 'preserve'],
  ['svg:tspan', 'edit'],
  ['svg:unknown', 'preserve-hidden'],
  ['svg:use', 'edit'],
  ['svg:video', 'active'],
  ['svg:view', 'edit'],
  ['svg:vkern', 'preserve-hidden'],
  ['xhtml:*', 'preserve-hidden'],
  ['xhtml:a', 'preserve'],
  ['xhtml:abbr', 'edit'],
  ['xhtml:address', 'edit'],
  ['xhtml:article', 'edit'],
  ['xhtml:aside', 'edit'],
  ['xhtml:audio', 'active'],
  ['xhtml:b', 'edit'],
  ['xhtml:base', 'active'],
  ['xhtml:bdi', 'edit'],
  ['xhtml:bdo', 'edit'],
  ['xhtml:blockquote', 'edit'],
  ['xhtml:br', 'edit'],
  ['xhtml:button', 'active'],
  ['xhtml:canvas', 'active'],
  ['xhtml:caption', 'edit'],
  ['xhtml:cite', 'edit'],
  ['xhtml:code', 'edit'],
  ['xhtml:col', 'edit'],
  ['xhtml:colgroup', 'edit'],
  ['xhtml:data', 'edit'],
  ['xhtml:dd', 'edit'],
  ['xhtml:del', 'edit'],
  ['xhtml:dfn', 'edit'],
  ['xhtml:div', 'edit'],
  ['xhtml:dl', 'edit'],
  ['xhtml:dt', 'edit'],
  ['xhtml:em', 'edit'],
  ['xhtml:embed', 'active'],
  ['xhtml:figcaption', 'edit'],
  ['xhtml:figure', 'edit'],
  ['xhtml:footer', 'edit'],
  ['xhtml:form', 'active'],
  ['xhtml:frame', 'active'],
  ['xhtml:frameset', 'active'],
  ['xhtml:h1', 'edit'],
  ['xhtml:h2', 'edit'],
  ['xhtml:h3', 'edit'],
  ['xhtml:h4', 'edit'],
  ['xhtml:h5', 'edit'],
  ['xhtml:h6', 'edit'],
  ['xhtml:header', 'edit'],
  ['xhtml:hr', 'edit'],
  ['xhtml:i', 'edit'],
  ['xhtml:iframe', 'active'],
  ['xhtml:img', 'edit'],
  ['xhtml:input', 'active'],
  ['xhtml:ins', 'edit'],
  ['xhtml:kbd', 'edit'],
  ['xhtml:li', 'edit'],
  ['xhtml:link', 'active'],
  ['xhtml:main', 'edit'],
  ['xhtml:mark', 'edit'],
  ['xhtml:meta', 'active'],
  ['xhtml:nav', 'edit'],
  ['xhtml:object', 'active'],
  ['xhtml:ol', 'edit'],
  ['xhtml:p', 'edit'],
  ['xhtml:portal', 'active'],
  ['xhtml:pre', 'edit'],
  ['xhtml:q', 'edit'],
  ['xhtml:rp', 'edit'],
  ['xhtml:rt', 'edit'],
  ['xhtml:ruby', 'edit'],
  ['xhtml:s', 'edit'],
  ['xhtml:samp', 'edit'],
  ['xhtml:script', 'active'],
  ['xhtml:section', 'edit'],
  ['xhtml:select', 'active'],
  ['xhtml:small', 'edit'],
  ['xhtml:source', 'active'],
  ['xhtml:span', 'edit'],
  ['xhtml:strong', 'edit'],
  ['xhtml:style', 'active'],
  ['xhtml:sub', 'edit'],
  ['xhtml:sup', 'edit'],
  ['xhtml:table', 'edit'],
  ['xhtml:tbody', 'edit'],
  ['xhtml:td', 'edit'],
  ['xhtml:textarea', 'active'],
  ['xhtml:tfoot', 'edit'],
  ['xhtml:th', 'edit'],
  ['xhtml:thead', 'edit'],
  ['xhtml:time', 'edit'],
  ['xhtml:tr', 'edit'],
  ['xhtml:track', 'active'],
  ['xhtml:u', 'edit'],
  ['xhtml:ul', 'edit'],
  ['xhtml:var', 'edit'],
  ['xhtml:video', 'active'],
  ['xhtml:wbr', 'edit'],
]);

/**
 * Every classified attribute: 'svg:fill', 'svg:xlink:href', 'xhtml:src', patterns such as
 * 'svg:on*', 'svg:data-*' and 'svg:(other)', and per-element overrides as 'svg:type@script'.
 */
export const ATTRIBUTE_CLASS: ReadonlyMap<string, LedgerClass> = new Map<string, LedgerClass>([
  ['svg:(other)', 'preserve-hidden'],
  ['svg:about', 'preserve-hidden'],
  ['svg:accent-height', 'preserve-hidden'],
  ['svg:accumulate', 'edit'],
  ['svg:additive', 'edit'],
  ['svg:alignment-baseline', 'edit'],
  ['svg:alphabetic', 'preserve-hidden'],
  ['svg:amplitude', 'edit'],
  ['svg:arabic-form', 'preserve-hidden'],
  ['svg:aria-*', 'edit'],
  ['svg:ascent', 'preserve-hidden'],
  ['svg:attributeName', 'edit'],
  ['svg:attributeType', 'edit'],
  ['svg:azimuth', 'edit'],
  ['svg:bandwidth', 'preserve-hidden'],
  ['svg:baseFrequency', 'edit'],
  ['svg:baseProfile', 'preserve-hidden'],
  ['svg:baseline-shift', 'edit'],
  ['svg:bbox', 'preserve-hidden'],
  ['svg:begin', 'edit'],
  ['svg:bias', 'edit'],
  ['svg:by', 'edit'],
  ['svg:calcMode', 'edit'],
  ['svg:cap-height', 'preserve-hidden'],
  ['svg:class', 'edit'],
  ['svg:clip', 'preserve'],
  ['svg:clip-path', 'edit'],
  ['svg:clip-rule', 'edit'],
  ['svg:clipPathUnits', 'edit'],
  ['svg:color', 'edit'],
  ['svg:color-interpolation', 'edit'],
  ['svg:color-interpolation-filters', 'edit'],
  ['svg:color-profile', 'preserve-hidden'],
  ['svg:color-rendering', 'preserve'],
  ['svg:content', 'preserve-hidden'],
  ['svg:contentScriptType', 'preserve-hidden'],
  ['svg:contentStyleType', 'preserve-hidden'],
  ['svg:crossorigin', 'preserve-hidden'],
  ['svg:cursor', 'edit'],
  ['svg:cx', 'edit'],
  ['svg:cy', 'edit'],
  ['svg:d', 'edit'],
  ['svg:data-*', 'preserve'],
  ['svg:datatype', 'preserve-hidden'],
  ['svg:defaultAction', 'active'],
  ['svg:descent', 'preserve-hidden'],
  ['svg:diffuseConstant', 'edit'],
  ['svg:direction', 'edit'],
  ['svg:display', 'edit'],
  ['svg:divisor', 'edit'],
  ['svg:dominant-baseline', 'edit'],
  ['svg:download', 'edit'],
  ['svg:dur', 'edit'],
  ['svg:dx', 'edit'],
  ['svg:dx@feDropShadow', 'edit'],
  ['svg:dx@feOffset', 'edit'],
  ['svg:dy', 'edit'],
  ['svg:dy@feDropShadow', 'edit'],
  ['svg:dy@feOffset', 'edit'],
  ['svg:edgeMode', 'edit'],
  ['svg:editable', 'preserve-hidden'],
  ['svg:elevation', 'edit'],
  ['svg:enable-background', 'preserve-hidden'],
  ['svg:end', 'edit'],
  ['svg:event', 'active'],
  ['svg:exponent', 'edit'],
  ['svg:externalResourcesRequired', 'preserve-hidden'],
  ['svg:fill', 'edit'],
  ['svg:fill-opacity', 'edit'],
  ['svg:fill-rule', 'edit'],
  ['svg:fill@animate', 'edit'],
  ['svg:fill@animateColor', 'edit'],
  ['svg:fill@animateMotion', 'edit'],
  ['svg:fill@animateTransform', 'edit'],
  ['svg:fill@animation', 'edit'],
  ['svg:fill@audio', 'edit'],
  ['svg:fill@set', 'edit'],
  ['svg:fill@video', 'edit'],
  ['svg:filter', 'edit'],
  ['svg:filterRes', 'preserve-hidden'],
  ['svg:filterUnits', 'edit'],
  ['svg:flood-color', 'edit'],
  ['svg:flood-opacity', 'edit'],
  ['svg:focusHighlight', 'preserve-hidden'],
  ['svg:focusable', 'preserve-hidden'],
  ['svg:font-family', 'edit'],
  ['svg:font-size', 'edit'],
  ['svg:font-size-adjust', 'edit'],
  ['svg:font-stretch', 'edit'],
  ['svg:font-style', 'edit'],
  ['svg:font-variant', 'edit'],
  ['svg:font-weight', 'edit'],
  ['svg:format', 'preserve-hidden'],
  ['svg:fr', 'edit'],
  ['svg:from', 'edit'],
  ['svg:fx', 'edit'],
  ['svg:fy', 'edit'],
  ['svg:g1', 'preserve-hidden'],
  ['svg:g2', 'preserve-hidden'],
  ['svg:glyph-name', 'preserve-hidden'],
  ['svg:glyph-orientation-horizontal', 'preserve'],
  ['svg:glyph-orientation-vertical', 'preserve'],
  ['svg:glyphRef', 'preserve-hidden'],
  ['svg:gradientTransform', 'edit'],
  ['svg:gradientUnits', 'edit'],
  ['svg:handler', 'active'],
  ['svg:hanging', 'preserve-hidden'],
  ['svg:height', 'edit'],
  ['svg:height@feBlend', 'edit'],
  ['svg:height@feColorMatrix', 'edit'],
  ['svg:height@feComponentTransfer', 'edit'],
  ['svg:height@feComposite', 'edit'],
  ['svg:height@feConvolveMatrix', 'edit'],
  ['svg:height@feDiffuseLighting', 'edit'],
  ['svg:height@feDisplacementMap', 'edit'],
  ['svg:height@feDropShadow', 'edit'],
  ['svg:height@feFlood', 'edit'],
  ['svg:height@feGaussianBlur', 'edit'],
  ['svg:height@feImage', 'edit'],
  ['svg:height@feMerge', 'edit'],
  ['svg:height@feMorphology', 'edit'],
  ['svg:height@feOffset', 'edit'],
  ['svg:height@feSpecularLighting', 'edit'],
  ['svg:height@feTile', 'edit'],
  ['svg:height@feTurbulence', 'edit'],
  ['svg:height@filter', 'edit'],
  ['svg:height@foreignObject', 'edit'],
  ['svg:height@image', 'edit'],
  ['svg:height@mask', 'edit'],
  ['svg:height@pattern', 'edit'],
  ['svg:height@symbol', 'edit'],
  ['svg:height@use', 'edit'],
  ['svg:horiz-adv-x', 'preserve-hidden'],
  ['svg:horiz-origin-x', 'preserve-hidden'],
  ['svg:horiz-origin-y', 'preserve-hidden'],
  ['svg:href', 'edit'],
  ['svg:href@a', 'edit'],
  ['svg:href@animate', 'edit'],
  ['svg:href@animateMotion', 'edit'],
  ['svg:href@animateTransform', 'edit'],
  ['svg:href@feImage', 'edit'],
  ['svg:href@image', 'edit'],
  ['svg:href@mpath', 'edit'],
  ['svg:href@pattern', 'edit'],
  ['svg:href@set', 'edit'],
  ['svg:href@textPath', 'edit'],
  ['svg:href@use', 'edit'],
  ['svg:hreflang', 'edit'],
  ['svg:id', 'edit'],
  ['svg:ideographic', 'preserve-hidden'],
  ['svg:image-rendering', 'edit'],
  ['svg:in', 'edit'],
  ['svg:in2', 'edit'],
  ['svg:initialVisibility', 'preserve-hidden'],
  ['svg:intercept', 'edit'],
  ['svg:k', 'preserve-hidden'],
  ['svg:k1', 'edit'],
  ['svg:k2', 'edit'],
  ['svg:k3', 'edit'],
  ['svg:k4', 'edit'],
  ['svg:kernelMatrix', 'edit'],
  ['svg:kernelUnitLength', 'edit'],
  ['svg:kerning', 'preserve'],
  ['svg:keyPoints', 'edit'],
  ['svg:keySplines', 'edit'],
  ['svg:keyTimes', 'edit'],
  ['svg:lang', 'edit'],
  ['svg:lengthAdjust', 'edit'],
  ['svg:letter-spacing', 'edit'],
  ['svg:lighting-color', 'edit'],
  ['svg:limitingConeAngle', 'edit'],
  ['svg:local', 'preserve-hidden'],
  ['svg:marker-end', 'edit'],
  ['svg:marker-mid', 'edit'],
  ['svg:marker-start', 'edit'],
  ['svg:markerHeight', 'edit'],
  ['svg:markerUnits', 'edit'],
  ['svg:markerWidth', 'edit'],
  ['svg:mask', 'edit'],
  ['svg:mask-type', 'edit'],
  ['svg:maskContentUnits', 'edit'],
  ['svg:maskUnits', 'edit'],
  ['svg:mathematical', 'preserve-hidden'],
  ['svg:max', 'edit'],
  ['svg:media', 'edit'],
  ['svg:mediaCharacterEncoding', 'preserve-hidden'],
  ['svg:mediaContentEncodings', 'preserve-hidden'],
  ['svg:mediaSize', 'preserve-hidden'],
  ['svg:mediaTime', 'preserve-hidden'],
  ['svg:method', 'edit'],
  ['svg:min', 'edit'],
  ['svg:mode', 'edit'],
  ['svg:name', 'preserve-hidden'],
  ['svg:nav-down', 'preserve-hidden'],
  ['svg:nav-down-left', 'preserve-hidden'],
  ['svg:nav-down-right', 'preserve-hidden'],
  ['svg:nav-left', 'preserve-hidden'],
  ['svg:nav-next', 'preserve-hidden'],
  ['svg:nav-prev', 'preserve-hidden'],
  ['svg:nav-right', 'preserve-hidden'],
  ['svg:nav-up', 'preserve-hidden'],
  ['svg:nav-up-left', 'preserve-hidden'],
  ['svg:nav-up-right', 'preserve-hidden'],
  ['svg:numOctaves', 'edit'],
  ['svg:observer', 'active'],
  ['svg:offset', 'edit'],
  ['svg:offset@feFuncA', 'edit'],
  ['svg:offset@feFuncB', 'edit'],
  ['svg:offset@feFuncG', 'edit'],
  ['svg:offset@feFuncR', 'edit'],
  ['svg:on*', 'active'],
  ['svg:opacity', 'edit'],
  ['svg:operator', 'edit'],
  ['svg:order', 'edit'],
  ['svg:orient', 'edit'],
  ['svg:orientation', 'preserve-hidden'],
  ['svg:origin', 'preserve-hidden'],
  ['svg:overflow', 'edit'],
  ['svg:overlay', 'preserve-hidden'],
  ['svg:overline-position', 'preserve-hidden'],
  ['svg:overline-thickness', 'preserve-hidden'],
  ['svg:paint-order', 'edit'],
  ['svg:panose-1', 'preserve-hidden'],
  ['svg:path', 'edit'],
  ['svg:path@textPath', 'edit'],
  ['svg:pathLength', 'edit'],
  ['svg:patternContentUnits', 'edit'],
  ['svg:patternTransform', 'edit'],
  ['svg:patternUnits', 'edit'],
  ['svg:phase', 'active'],
  ['svg:ping', 'active'],
  ['svg:playbackOrder', 'preserve-hidden'],
  ['svg:playbackorder', 'preserve-hidden'],
  ['svg:pointer-events', 'edit'],
  ['svg:points', 'edit'],
  ['svg:pointsAtX', 'edit'],
  ['svg:pointsAtY', 'edit'],
  ['svg:pointsAtZ', 'edit'],
  ['svg:preserveAlpha', 'edit'],
  ['svg:preserveAspectRatio', 'edit'],
  ['svg:preserveAspectRatio@feImage', 'edit'],
  ['svg:preserveAspectRatio@image', 'edit'],
  ['svg:preserveAspectRatio@marker', 'edit'],
  ['svg:preserveAspectRatio@pattern', 'edit'],
  ['svg:primitiveUnits', 'edit'],
  ['svg:propagate', 'active'],
  ['svg:property', 'preserve-hidden'],
  ['svg:r', 'edit'],
  ['svg:radius', 'edit'],
  ['svg:refX', 'edit'],
  ['svg:refX@marker', 'edit'],
  ['svg:refY', 'edit'],
  ['svg:refY@marker', 'edit'],
  ['svg:referrerpolicy', 'edit'],
  ['svg:rel', 'preserve-hidden'],
  ['svg:rendering-intent', 'preserve-hidden'],
  ['svg:repeatCount', 'edit'],
  ['svg:repeatDur', 'edit'],
  ['svg:requiredExtensions', 'edit'],
  ['svg:requiredFeatures', 'preserve'],
  ['svg:requiredFonts', 'preserve-hidden'],
  ['svg:requiredFormats', 'preserve-hidden'],
  ['svg:resource', 'preserve-hidden'],
  ['svg:restart', 'edit'],
  ['svg:result', 'edit'],
  ['svg:rev', 'preserve-hidden'],
  ['svg:role', 'edit'],
  ['svg:rotate', 'edit'],
  ['svg:rotate@animateMotion', 'edit'],
  ['svg:rx', 'edit'],
  ['svg:ry', 'edit'],
  ['svg:scale', 'edit'],
  ['svg:seed', 'edit'],
  ['svg:shape-rendering', 'edit'],
  ['svg:side', 'edit'],
  ['svg:slope', 'edit'],
  ['svg:slope@font-face', 'preserve-hidden'],
  ['svg:snapshotTime', 'preserve-hidden'],
  ['svg:spacing', 'edit'],
  ['svg:specularConstant', 'edit'],
  ['svg:specularExponent', 'edit'],
  ['svg:spreadMethod', 'edit'],
  ['svg:startOffset', 'edit'],
  ['svg:stdDeviation', 'edit'],
  ['svg:stemh', 'preserve-hidden'],
  ['svg:stemv', 'preserve-hidden'],
  ['svg:stitchTiles', 'edit'],
  ['svg:stop-color', 'edit'],
  ['svg:stop-opacity', 'edit'],
  ['svg:strikethrough-position', 'preserve-hidden'],
  ['svg:strikethrough-thickness', 'preserve-hidden'],
  ['svg:string', 'preserve-hidden'],
  ['svg:stroke', 'edit'],
  ['svg:stroke-dasharray', 'edit'],
  ['svg:stroke-dashoffset', 'edit'],
  ['svg:stroke-linecap', 'edit'],
  ['svg:stroke-linejoin', 'edit'],
  ['svg:stroke-miterlimit', 'edit'],
  ['svg:stroke-opacity', 'edit'],
  ['svg:stroke-width', 'edit'],
  ['svg:style', 'edit'],
  ['svg:surfaceScale', 'edit'],
  ['svg:syncBehavior', 'preserve-hidden'],
  ['svg:syncBehaviorDefault', 'preserve-hidden'],
  ['svg:syncMaster', 'preserve-hidden'],
  ['svg:syncTolerance', 'preserve-hidden'],
  ['svg:syncToleranceDefault', 'preserve-hidden'],
  ['svg:systemLanguage', 'edit'],
  ['svg:tabindex', 'edit'],
  ['svg:tableValues', 'edit'],
  ['svg:target', 'edit'],
  ['svg:target@listener', 'active'],
  ['svg:targetX', 'edit'],
  ['svg:targetY', 'edit'],
  ['svg:text-anchor', 'edit'],
  ['svg:text-decoration', 'edit'],
  ['svg:text-overflow', 'edit'],
  ['svg:text-rendering', 'edit'],
  ['svg:textLength', 'edit'],
  ['svg:timelineBegin', 'preserve-hidden'],
  ['svg:timelinebegin', 'preserve-hidden'],
  ['svg:title', 'preserve'],
  ['svg:to', 'edit'],
  ['svg:transform', 'edit'],
  ['svg:transform-origin', 'edit'],
  ['svg:transformBehavior', 'preserve-hidden'],
  ['svg:type', 'edit'],
  ['svg:type@a', 'edit'],
  ['svg:type@animateTransform', 'edit'],
  ['svg:type@audio', 'preserve-hidden'],
  ['svg:type@handler', 'active'],
  ['svg:type@image', 'preserve-hidden'],
  ['svg:type@script', 'active'],
  ['svg:type@style', 'edit'],
  ['svg:type@video', 'preserve-hidden'],
  ['svg:typeof', 'preserve-hidden'],
  ['svg:u1', 'preserve-hidden'],
  ['svg:u2', 'preserve-hidden'],
  ['svg:underline-position', 'preserve-hidden'],
  ['svg:underline-thickness', 'preserve-hidden'],
  ['svg:unicode', 'preserve-hidden'],
  ['svg:unicode-bidi', 'edit'],
  ['svg:unicode-range', 'preserve-hidden'],
  ['svg:units-per-em', 'preserve-hidden'],
  ['svg:v-alphabetic', 'preserve-hidden'],
  ['svg:v-hanging', 'preserve-hidden'],
  ['svg:v-ideographic', 'preserve-hidden'],
  ['svg:v-mathematical', 'preserve-hidden'],
  ['svg:values', 'edit'],
  ['svg:values@feColorMatrix', 'edit'],
  ['svg:vector-effect', 'edit'],
  ['svg:version', 'preserve-hidden'],
  ['svg:vert-adv-y', 'preserve-hidden'],
  ['svg:vert-origin-x', 'preserve-hidden'],
  ['svg:vert-origin-y', 'preserve-hidden'],
  ['svg:viewBox', 'edit'],
  ['svg:viewBox@marker', 'edit'],
  ['svg:viewBox@pattern', 'edit'],
  ['svg:viewTarget', 'preserve-hidden'],
  ['svg:visibility', 'edit'],
  ['svg:white-space', 'edit'],
  ['svg:width', 'edit'],
  ['svg:width@feBlend', 'edit'],
  ['svg:width@feColorMatrix', 'edit'],
  ['svg:width@feComponentTransfer', 'edit'],
  ['svg:width@feComposite', 'edit'],
  ['svg:width@feConvolveMatrix', 'edit'],
  ['svg:width@feDiffuseLighting', 'edit'],
  ['svg:width@feDisplacementMap', 'edit'],
  ['svg:width@feDropShadow', 'edit'],
  ['svg:width@feFlood', 'edit'],
  ['svg:width@feGaussianBlur', 'edit'],
  ['svg:width@feImage', 'edit'],
  ['svg:width@feMerge', 'edit'],
  ['svg:width@feMorphology', 'edit'],
  ['svg:width@feOffset', 'edit'],
  ['svg:width@feSpecularLighting', 'edit'],
  ['svg:width@feTile', 'edit'],
  ['svg:width@feTurbulence', 'edit'],
  ['svg:width@filter', 'edit'],
  ['svg:width@foreignObject', 'edit'],
  ['svg:width@image', 'edit'],
  ['svg:width@mask', 'edit'],
  ['svg:width@pattern', 'edit'],
  ['svg:width@symbol', 'edit'],
  ['svg:width@use', 'edit'],
  ['svg:widths', 'preserve-hidden'],
  ['svg:word-spacing', 'edit'],
  ['svg:writing-mode', 'edit'],
  ['svg:x', 'edit'],
  ['svg:x-height', 'preserve-hidden'],
  ['svg:x1', 'edit'],
  ['svg:x2', 'edit'],
  ['svg:x@feBlend', 'edit'],
  ['svg:x@feColorMatrix', 'edit'],
  ['svg:x@feComponentTransfer', 'edit'],
  ['svg:x@feComposite', 'edit'],
  ['svg:x@feConvolveMatrix', 'edit'],
  ['svg:x@feDiffuseLighting', 'edit'],
  ['svg:x@feDisplacementMap', 'edit'],
  ['svg:x@feDropShadow', 'edit'],
  ['svg:x@feFlood', 'edit'],
  ['svg:x@feGaussianBlur', 'edit'],
  ['svg:x@feImage', 'edit'],
  ['svg:x@feMerge', 'edit'],
  ['svg:x@feMorphology', 'edit'],
  ['svg:x@feOffset', 'edit'],
  ['svg:x@fePointLight', 'edit'],
  ['svg:x@feSpecularLighting', 'edit'],
  ['svg:x@feSpotLight', 'edit'],
  ['svg:x@feTile', 'edit'],
  ['svg:x@feTurbulence', 'edit'],
  ['svg:x@filter', 'edit'],
  ['svg:x@foreignObject', 'edit'],
  ['svg:x@image', 'edit'],
  ['svg:x@mask', 'edit'],
  ['svg:x@pattern', 'edit'],
  ['svg:x@symbol', 'edit'],
  ['svg:x@use', 'edit'],
  ['svg:xChannelSelector', 'edit'],
  ['svg:xlink:actuate', 'preserve-hidden'],
  ['svg:xlink:arcrole', 'preserve-hidden'],
  ['svg:xlink:href', 'edit'],
  ['svg:xlink:href@a', 'edit'],
  ['svg:xlink:href@animate', 'edit'],
  ['svg:xlink:href@animateMotion', 'edit'],
  ['svg:xlink:href@animateTransform', 'edit'],
  ['svg:xlink:href@feImage', 'edit'],
  ['svg:xlink:href@image', 'edit'],
  ['svg:xlink:href@mpath', 'edit'],
  ['svg:xlink:href@pattern', 'edit'],
  ['svg:xlink:href@set', 'edit'],
  ['svg:xlink:href@textPath', 'edit'],
  ['svg:xlink:href@use', 'edit'],
  ['svg:xlink:role', 'preserve-hidden'],
  ['svg:xlink:show', 'preserve-hidden'],
  ['svg:xlink:title', 'edit'],
  ['svg:xlink:type', 'preserve-hidden'],
  ['svg:xml:base', 'active'],
  ['svg:xml:id', 'preserve-hidden'],
  ['svg:xml:lang', 'edit'],
  ['svg:xml:space', 'edit'],
  ['svg:y', 'edit'],
  ['svg:y1', 'edit'],
  ['svg:y2', 'edit'],
  ['svg:y@feBlend', 'edit'],
  ['svg:y@feColorMatrix', 'edit'],
  ['svg:y@feComponentTransfer', 'edit'],
  ['svg:y@feComposite', 'edit'],
  ['svg:y@feConvolveMatrix', 'edit'],
  ['svg:y@feDiffuseLighting', 'edit'],
  ['svg:y@feDisplacementMap', 'edit'],
  ['svg:y@feDropShadow', 'edit'],
  ['svg:y@feFlood', 'edit'],
  ['svg:y@feGaussianBlur', 'edit'],
  ['svg:y@feImage', 'edit'],
  ['svg:y@feMerge', 'edit'],
  ['svg:y@feMorphology', 'edit'],
  ['svg:y@feOffset', 'edit'],
  ['svg:y@fePointLight', 'edit'],
  ['svg:y@feSpecularLighting', 'edit'],
  ['svg:y@feSpotLight', 'edit'],
  ['svg:y@feTile', 'edit'],
  ['svg:y@feTurbulence', 'edit'],
  ['svg:y@filter', 'edit'],
  ['svg:y@foreignObject', 'edit'],
  ['svg:y@image', 'edit'],
  ['svg:y@mask', 'edit'],
  ['svg:y@pattern', 'edit'],
  ['svg:y@symbol', 'edit'],
  ['svg:y@use', 'edit'],
  ['svg:yChannelSelector', 'edit'],
  ['svg:z', 'edit'],
  ['svg:zoomAndPan', 'preserve-hidden'],
  ['xhtml:align', 'preserve'],
  ['xhtml:alt', 'edit'],
  ['xhtml:bgcolor', 'preserve'],
  ['xhtml:border', 'preserve'],
  ['xhtml:cellpadding', 'preserve'],
  ['xhtml:cellspacing', 'preserve'],
  ['xhtml:cite', 'preserve-hidden'],
  ['xhtml:class', 'edit'],
  ['xhtml:colspan', 'edit'],
  ['xhtml:datetime', 'preserve-hidden'],
  ['xhtml:dir', 'edit'],
  ['xhtml:height', 'edit'],
  ['xhtml:height@table', 'preserve'],
  ['xhtml:height@td', 'preserve'],
  ['xhtml:height@th', 'preserve'],
  ['xhtml:height@tr', 'preserve'],
  ['xhtml:hidden', 'edit'],
  ['xhtml:href', 'edit'],
  ['xhtml:id', 'edit'],
  ['xhtml:lang', 'edit'],
  ['xhtml:popover', 'preserve-hidden'],
  ['xhtml:reversed', 'preserve'],
  ['xhtml:rowspan', 'edit'],
  ['xhtml:span', 'preserve'],
  ['xhtml:src', 'edit'],
  ['xhtml:start', 'preserve'],
  ['xhtml:style', 'edit'],
  ['xhtml:target', 'edit'],
  ['xhtml:title', 'edit'],
  ['xhtml:valign', 'preserve'],
  ['xhtml:value', 'preserve'],
  ['xhtml:width', 'edit'],
  ['xhtml:width@col', 'preserve'],
  ['xhtml:width@table', 'preserve'],
  ['xhtml:width@td', 'preserve'],
  ['xhtml:width@th', 'preserve'],
]);

/** Every classified namespace by URI; '*' is any other namespace. */
export const NAMESPACE_CLASS: ReadonlyMap<string, LedgerClass> = new Map<string, LedgerClass>([
  ['*', 'preserve-hidden'],
  ['http://creativecommons.org/ns#', 'preserve-hidden'],
  ['http://ns.adobe.com/AdobeIllustrator/10.0/', 'preserve-hidden'],
  ['http://ns.adobe.com/Extensibility/1.0/', 'preserve-hidden'],
  ['http://ns.adobe.com/Graphs/1.0/', 'preserve-hidden'],
  ['http://ns.adobe.com/SaveForWeb/1.0/', 'preserve-hidden'],
  ['http://purl.org/dc/elements/1.1/', 'preserve-hidden'],
  ['http://purl.org/dc/terms/', 'preserve-hidden'],
  ['http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd', 'preserve-hidden'],
  ['http://web.resource.org/cc/', 'preserve-hidden'],
  ['http://www.bohemiancoding.com/sketch/ns', 'preserve-hidden'],
  ['http://www.inkscape.org/namespaces/inkscape', 'preserve-hidden'],
  ['http://www.serif.com/', 'preserve-hidden'],
  ['http://www.w3.org/1998/Math/MathML', 'preserve-hidden'],
  ['http://www.w3.org/1999/02/22-rdf-syntax-ns#', 'preserve-hidden'],
  ['http://www.w3.org/1999/xhtml', 'edit'],
  ['http://www.w3.org/1999/xlink', 'edit'],
  ['http://www.w3.org/2000/svg', 'edit'],
  ['http://www.w3.org/2001/xml-events', 'active'],
  ['http://www.w3.org/XML/1998/namespace', 'edit'],
  ['https://mmaggitti.github.io/draw/ns', 'preserve-hidden'],
]);
