//! FSRS-6: the memory model behind the scheduler.
//!
//! A card's memory is two numbers. **Stability** S is the number of days until the chance of
//! recalling it falls to 90%. **Difficulty** D, from 1 to 10, is how hard its stability is to
//! grow. **Retrievability** R is that chance at a given moment, from S and the days since the last
//! review. Each review, graded Again, Hard, Good or Easy, moves S and D.
//!
//! This is a port of fsrs-rs (the reference implementation), in f64 where fsrs-rs computes in f32.
//! `tests/fsrs.rs` holds it to values generated by fsrs-rs itself (`tools/fsrs-vectors`).

/// FSRS-6's 21 default parameters, w0 to w20, as fsrs-rs ships them.
pub const DEFAULT_PARAMETERS: [f64; 21] = [
    0.212, 1.2931, 2.3065, 8.2956, 6.4133, 0.8334, 3.0194, 0.001, 1.8722, 0.1666, 0.796, 1.4835, 0.0614, 0.2629,
    1.6483, 0.6014, 1.8729, 0.5425, 0.0912, 0.0658, 0.1542,
];

/// Stability is kept within these bounds, in days.
pub const S_MIN: f64 = 0.001;
pub const S_MAX: f64 = 36_500.0;
/// Difficulty is kept within these bounds.
pub const D_MIN: f64 = 1.0;
pub const D_MAX: f64 = 10.0;

/// A self-grade. The numbers are FSRS's ratings.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Rating {
    Again = 1,
    Hard = 2,
    Good = 3,
    Easy = 4,
}

impl Rating {
    pub fn from_u8(value: u8) -> Option<Self> {
        match value {
            1 => Some(Self::Again),
            2 => Some(Self::Hard),
            3 => Some(Self::Good),
            4 => Some(Self::Easy),
            _ => None,
        }
    }
    fn value(self) -> f64 {
        f64::from(self as u8)
    }
}

/// A card's memory after its latest review.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct MemoryState {
    pub stability: f64,
    pub difficulty: f64,
}

/// The model with one set of parameters.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Fsrs {
    w: [f64; 21],
}

impl Default for Fsrs {
    fn default() -> Self {
        Self { w: DEFAULT_PARAMETERS }
    }
}

impl Fsrs {
    pub fn new(parameters: [f64; 21]) -> Self {
        Self { w: parameters }
    }

    /// The forgetting curve's decay, w20.
    fn decay(&self) -> f64 {
        -self.w[20]
    }

    /// Chosen so that R is exactly 0.9 when the elapsed days equal the stability.
    fn factor(&self) -> f64 {
        0.9f64.powf(1.0 / self.decay()) - 1.0
    }

    /// The chance of recall after `days` since the last review, for a card with `stability`.
    pub fn retrievability(&self, days: f64, stability: f64) -> f64 {
        (1.0 + self.factor() * days.max(0.0) / stability).powf(self.decay())
    }

    /// Days until retrievability falls to `desired_retention` (unrounded).
    pub fn interval(&self, stability: f64, desired_retention: f64) -> f64 {
        stability / self.factor() * (desired_retention.powf(1.0 / self.decay()) - 1.0)
    }

    fn init_stability(&self, rating: Rating) -> f64 {
        self.w[rating as usize - 1].clamp(S_MIN, S_MAX)
    }

    fn init_difficulty_raw(&self, rating: Rating) -> f64 {
        self.w[4] - (self.w[5] * (rating.value() - 1.0)).exp() + 1.0
    }

    /// The memory after a card's first review.
    pub fn first(&self, rating: Rating) -> MemoryState {
        MemoryState {
            stability: self.init_stability(rating),
            difficulty: self.init_difficulty_raw(rating).clamp(D_MIN, D_MAX),
        }
    }

    fn next_difficulty(&self, d: f64, rating: Rating) -> f64 {
        let delta = -self.w[6] * (rating.value() - 3.0);
        // Linear damping: the closer to 10, the smaller the step.
        let damped = d + (10.0 - d) * delta / 9.0;
        // Mean reversion toward the *unclamped* difficulty of a first "Easy" (below 1 with the
        // defaults), as fsrs-rs does; only the result is clamped.
        (self.w[7] * (self.init_difficulty_raw(Rating::Easy) - damped) + damped).clamp(D_MIN, D_MAX)
    }

    fn stability_after_success(&self, s: f64, d: f64, r: f64, rating: Rating) -> f64 {
        let hard_penalty = if rating == Rating::Hard { self.w[15] } else { 1.0 };
        let easy_bonus = if rating == Rating::Easy { self.w[16] } else { 1.0 };
        s * (self.w[8].exp() * (11.0 - d) * s.powf(-self.w[9]) * (((1.0 - r) * self.w[10]).exp() - 1.0) * hard_penalty * easy_bonus + 1.0)
    }

    fn stability_after_failure(&self, s: f64, d: f64, r: f64) -> f64 {
        let new_s = self.w[11] * d.powf(-self.w[12]) * ((s + 1.0).powf(self.w[13]) - 1.0) * ((1.0 - r) * self.w[14]).exp();
        // A lapse never leaves the card more stable than a same-day "Again" would.
        new_s.min(s / (self.w[17] * self.w[18]).exp())
    }

    /// A second review on the same day: FSRS-6's short-term stability. Only "Again" can lower
    /// stability here; Hard, Good and Easy never do (fsrs-rs clamps from Hard up, not from Good).
    fn stability_short_term(&self, s: f64, rating: Rating) -> f64 {
        let sinc = (self.w[17] * (rating.value() - 3.0 + self.w[18])).exp() * s.powf(-self.w[19]);
        s * if rating == Rating::Again { sinc } else { sinc.max(1.0) }
    }

    /// The memory after a review graded `rating`, `elapsed_days` whole days after the previous one.
    /// A same-day review (0 days) takes the short-term path whatever the grade, "Again" included.
    pub fn next(&self, state: MemoryState, elapsed_days: u32, rating: Rating) -> MemoryState {
        // A stored state outside the bounds is brought inside them before use, as fsrs-rs does.
        let s = state.stability.clamp(S_MIN, S_MAX);
        let d = state.difficulty.clamp(D_MIN, D_MAX);
        let stability = if elapsed_days == 0 {
            self.stability_short_term(s, rating)
        } else {
            let r = self.retrievability(f64::from(elapsed_days), s);
            if rating == Rating::Again { self.stability_after_failure(s, d, r) } else { self.stability_after_success(s, d, r, rating) }
        };
        MemoryState { stability: stability.clamp(S_MIN, S_MAX), difficulty: self.next_difficulty(d, rating) }
    }

    /// The memory after a whole history of (whole days since the previous review, rating); the
    /// first entry's days are ignored. `None` for an empty history (a new card).
    pub fn replay(&self, history: impl IntoIterator<Item = (u32, Rating)>) -> Option<MemoryState> {
        let mut state: Option<MemoryState> = None;
        for (days, rating) in history {
            state = Some(match state {
                None => self.first(rating),
                Some(prev) => self.next(prev, days, rating),
            });
        }
        state
    }
}
