#!/usr/bin/env node
// Builds every projects/<name>/ into _site/<name>/ and writes the launcher at _site/index.html.
//
//   static project — no "build" script in its package.json: copied as-is
//   built project  — `npm ci` (or `npm install` without a lockfile), then `npm run build` with
//                    BASE_PATH=/<name>/, then its dist/ is copied. Vite reads it as
//                    `base: process.env.BASE_PATH ?? "/"`, or every asset 404s under /<name>/.
//
// Folders starting with "_" or "." are drafts and are skipped. The launcher is generated from each
// project's built <title> and <meta name="description">, so it can't drift from the projects.

import { execFileSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PROJECTS = join(ROOT, 'projects');
const OUT = join(ROOT, '_site');
// Paths on this origin already served by their own repo (project sites win over the user site).
const RESERVED = new Set(['crossword-v1']);

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT);

const names = existsSync(PROJECTS)
  ? readdirSync(PROJECTS, { withFileTypes: true })
      .filter((d) => d.isDirectory() && !/^[_.]/.test(d.name))
      .map((d) => d.name)
      .sort()
  : [];

const cards = [];
for (const name of names) {
  if (RESERVED.has(name)) throw new Error(`projects/${name}: that path belongs to its own repo`);
  // Pages is case-sensitive and macOS is not; lowercase-only names avoid a local-works/live-404 split.
  if (!/^[a-z0-9][a-z0-9-]*$/.test(name)) throw new Error(`projects/${name}: use lowercase letters, digits, hyphens`);

  const src = join(PROJECTS, name);
  const dest = join(OUT, name);
  const pkgFile = join(src, 'package.json');
  const pkg = existsSync(pkgFile) ? JSON.parse(readFileSync(pkgFile, 'utf8')) : null;

  if (pkg?.scripts?.build) {
    const npm = (args) =>
      execFileSync('npm', args, { cwd: src, stdio: 'inherit', env: { ...process.env, BASE_PATH: `/${name}/` } });
    npm(existsSync(join(src, 'package-lock.json')) ? ['ci'] : ['install']);
    npm(['run', 'build']);
    cpSync(join(src, 'dist'), dest, { recursive: true });
  } else {
    cpSync(src, dest, { recursive: true, filter: (p) => !p.includes(`${sep}node_modules`) });
  }

  const entry = join(dest, 'index.html');
  if (!existsSync(entry)) throw new Error(`projects/${name}: no index.html in the built output`);
  const html = readFileSync(entry, 'utf8');
  cards.push({
    name,
    title: html.match(/<title>([^<]*)<\/title>/i)?.[1].trim() || name,
    description:
      html.match(/<meta\s+name=["']description["']\s+content=["']([^"']*)["']/i)?.[1] ??
      html.match(/<meta\s+content=["']([^"']*)["']\s+name=["']description["']/i)?.[1] ??
      '',
  });
  console.log(`built ${name}`);
}

writeFileSync(join(OUT, 'index.html'), launcher(cards));
console.log(`launcher: ${cards.length} project(s) → _site/index.html`);

function esc(s) {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
}

function launcher(cards) {
  const items = cards.length
    ? cards
        .map(
          (c) => `      <li><a href="${esc(c.name)}/">
        <span class="t">${esc(c.title)}</span>${c.description ? `
        <span class="d">${esc(c.description)}</span>` : ''}
      </a></li>`,
        )
        .join('\n')
    : '      <li class="empty">No projects yet.</li>';
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <meta name="theme-color" content="#F6F4EE" media="(prefers-color-scheme: light)">
  <meta name="theme-color" content="#111111" media="(prefers-color-scheme: dark)">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <meta name="description" content="Phone-first mini projects.">
  <link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='14' fill='%23233044'/%3E%3Crect x='14' y='14' width='16' height='16' rx='4' fill='%23fff'/%3E%3Crect x='34' y='14' width='16' height='16' rx='4' fill='%23fff' opacity='.45'/%3E%3Crect x='14' y='34' width='16' height='16' rx='4' fill='%23fff' opacity='.45'/%3E%3Crect x='34' y='34' width='16' height='16' rx='4' fill='%23fff' opacity='.45'/%3E%3C/svg%3E">
  <title>Projects</title>
  <!-- Generated by scripts/build-site.mjs — edit the generator, not this file. -->
  <style>
    :root { --bg: #F6F4EE; --card: #FFFFFF; --text: #1B1B1B; --muted: #5E5A52; --line: #E3DED3; --accent: #233044; }
    @media (prefers-color-scheme: dark) {
      :root { --bg: #111111; --card: #1C1C1E; --text: #F2F2F2; --muted: #A5A5AA; --line: #2C2C2E; --accent: #9DB4D6; }
    }
    * { box-sizing: border-box; }
    html { -webkit-text-size-adjust: 100%; }
    body {
      margin: 0; min-height: 100svh; background: var(--bg); color: var(--text);
      font: 17px/1.45 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      padding: calc(env(safe-area-inset-top) + 24px) calc(env(safe-area-inset-right) + 16px)
               calc(env(safe-area-inset-bottom) + 24px) calc(env(safe-area-inset-left) + 16px);
    }
    main { max-width: 560px; margin: 0 auto; }
    h1 { font-size: 28px; line-height: 1.2; margin: 0 0 4px; }
    p.sub { color: var(--muted); margin: 0 0 20px; }
    ul { list-style: none; margin: 0; padding: 0; display: grid; gap: 12px; }
    a {
      display: flex; flex-direction: column; justify-content: center; gap: 2px;
      min-height: 64px; padding: 14px 16px; border-radius: 14px;
      background: var(--card); border: 1px solid var(--line); color: inherit; text-decoration: none;
    }
    a:active { background: var(--line); }
    a:focus-visible { outline: 3px solid var(--accent); outline-offset: 2px; }
    .t { font-weight: 600; }
    .d { color: var(--muted); font-size: 15px; }
    .empty { color: var(--muted); }
  </style>
</head>
<body>
  <main>
    <h1>Projects</h1>
    <p class="sub">Phone-first mini projects.</p>
    <ul>
${items}
    </ul>
  </main>
</body>
</html>
`;
}
