//! The FSRS-6 port, held to values generated by fsrs-rs itself (`tools/fsrs-vectors`, fsrs =6.6.2).
//!
//! fsrs-rs computes in f32 and this port in f64, so they agree to a tolerance, not bit for bit:
//! relative 1e-4 on stability and intervals, 1e-5 on difficulty and retrievability. The worst case
//! measured was 1.1e-5, on a tiny stability after repeated lapses, where `(S + 1)^w13 - 1` cancels.

#![allow(clippy::unreadable_literal, clippy::excessive_precision)]

include!("data/fsrs_vectors.rs");

use srs_core::fsrs::{DEFAULT_PARAMETERS as PORT_PARAMETERS, Fsrs, MemoryState, Rating};

const REL_S: f64 = 1e-4;
const REL_D: f64 = 1e-5;
const REL_R: f64 = 1e-5;

fn close(got: f64, want: f64, rel: f64) -> bool {
    (got - want).abs() <= rel * want.abs() + 1e-9
}

/// Collects every mismatch, so one run shows them all; fails once at the end.
struct Mismatches(Vec<String>);

impl Mismatches {
    fn check(&mut self, what: impl FnOnce() -> String, got: f64, want: f64, rel: f64) {
        if !close(got, want, rel) {
            self.0.push(format!("{}: got {got}, want {want} (rel {:.2e})", what(), ((got - want) / want).abs()));
        }
    }
    fn assert_none(self, table: &str) {
        let shown: Vec<&String> = self.0.iter().take(12).collect();
        assert!(self.0.is_empty(), "{} {table} mismatch(es) against fsrs-rs {FSRS_VERSION}:\n{shown:#?}", self.0.len());
    }
}

#[test]
fn the_vectors_are_from_the_pinned_version() {
    assert_eq!(FSRS_VERSION, "6.6.2");
    assert!(HISTORIES.len() >= 50 && RETRIEVABILITY.len() >= 40 && NEXT_STATES.len() >= 20);
}

#[test]
fn default_parameters_match() {
    let mut m = Mismatches(Vec::new());
    for (i, (&got, &want)) in PORT_PARAMETERS.iter().zip(DEFAULT_PARAMETERS.iter()).enumerate() {
        m.check(|| format!("w{i}"), got, want, 1e-7);
    }
    m.assert_none("parameter");
}

#[test]
fn memory_state_after_every_review_of_every_history() {
    let fsrs = Fsrs::default();
    let mut m = Mismatches(Vec::new());
    let mut steps = 0;
    for h in HISTORIES {
        let mut state: Option<MemoryState> = None;
        for (i, step) in h.steps.iter().enumerate() {
            let Some(rating) = Rating::from_u8(step.rating) else {
                m.0.push(format!("{} step {i}: rating {} out of range", h.name, step.rating));
                break;
            };
            let next = match state {
                None => fsrs.first(rating),
                Some(prev) => fsrs.next(prev, step.delta_days, rating),
            };
            m.check(|| format!("{} step {i} stability", h.name), next.stability, step.stability, REL_S);
            m.check(|| format!("{} step {i} difficulty", h.name), next.difficulty, step.difficulty, REL_D);
            // Continue from fsrs-rs's own state, so one early difference can't cascade.
            state = Some(MemoryState { stability: step.stability, difficulty: step.difficulty });
            steps += 1;
        }
    }
    assert!(steps >= 500, "only {steps} steps checked");
    m.assert_none("history");
}

#[test]
fn retrievability() {
    let fsrs = Fsrs::default();
    let mut m = Mismatches(Vec::new());
    for r in RETRIEVABILITY {
        m.check(|| format!("R(S={}, t={})", r.stability, r.days), fsrs.retrievability(r.days, r.stability), r.retrievability, REL_R);
    }
    m.assert_none("retrievability");
}

#[test]
fn next_states_and_intervals() {
    let fsrs = Fsrs::default();
    let mut m = Mismatches(Vec::new());
    for (c, case) in NEXT_STATES.iter().enumerate() {
        let state = MemoryState { stability: case.stability, difficulty: case.difficulty };
        for (g, &(s, d, interval)) in case.next.iter().enumerate() {
            let Some(rating) = Rating::from_u8(g as u8 + 1) else { continue };
            let next = fsrs.next(state, case.days_elapsed, rating);
            m.check(|| format!("case {c} grade {} stability", g + 1), next.stability, s, REL_S);
            m.check(|| format!("case {c} grade {} difficulty", g + 1), next.difficulty, d, REL_D);
            m.check(|| format!("case {c} grade {} interval", g + 1), fsrs.interval(next.stability, case.desired_retention), interval, REL_S);
        }
    }
    m.assert_none("next-state");
}
